### ISSUE TITLE
['Forgot your password?' page] User can`t receive email with valid adress

### ISSUE THREAD

**Issue by danylo-basarab** [ita-social-projects/what-front#722]
**Environment:** 
http://localhost:8080/forgot-password
Windows 10 Pro
Google Chrome 91.0.4472.164
**Reproducible:** always

**Pre-conditions:**
1. WHAT project launched locally using npm.
2. User has an account.
3. 'Forgot your password?' page is opened. URL: 'http://localhost:8080/forgot-password'.

**Steps to reproduce:**
1. Enter the email, which is used on your account to 'Email address field
2. Click 'Send' button

**Actual result:**
- Error 'An error occurred under 'Send' button
- Error in console: Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://whatbackend.azurewebsites.net/api/accounts/password/forgot

**Expected result:** 
'Forgot password information' window is opened.
Email letter with link for recovering password was sent on your address

**Links:**
[TC-289](https://jira.softserve.academy/browse/DPWHAT-289)

**Labels to be added**
"Bug", Priority ("high"), Severity ("major"), Type ("Functional")

**Comment by Halyna-B** [comment]
This bug was fixed. When user enter the active email to 'Email address field and click 'Send' button - 'Forgot password information' window is open, email letter with link for recovering password is sending on user's address.

https://user-images.githubusercontent.com/79538541/133965906-2b8d5b84-d211-4fee-8dbc-656e4014cf8e.mp4
